### ISSUE TITLE
Awesome work! Lora finetuning 

### ISSUE THREAD

**Issue by mortium91** [ashleykleynhans/dreambooth-api#1]
Great work! Definitely gonna use this for dreambooth training :) do you also expect to support lora finetuning in the future??

**Comment by ashleykleynhans** [comment]
Thanks for the compliment, very much appreciated.

I haven't actually used this for Lora yet, I will look into that in future.

I believe this may be a better option for Lora training, but I don't think it has an API:

https://github.com/bmaltais/kohya_ss
